#!/bin/sh

# change first interface to wan
if [[ -z `ls /sys/class/net/|grep '^wan$'` ]] ; then
        wan=`ls /sys/class/net/|sort |grep enp|head -n1`
        ifconfig $wan down
        ip link set $wan name wan
        ifconfig wan up
fi

# add lan and set ipaddress
if [[ -z `ls /sys/class/net/|grep '^lan$'` ]] ; then
	/usr/sbin/brctl addbr lan
fi
/sbin/ifconfig lan up
/sbin/ip addr add $IPV4NET dev lan
/sbin/ip addr add $IPV6NET dev lan

# iptables 
# lan nat to wan
/sbin/ip6tables -t nat -A POSTROUTING -s fd00::/64 -o wan -j MASQUERADE
# allow ssh from lan
/sbin/ip6tables -A INPUT -s IPV6NET -p tcp -m tcp --dport 22 -j ACCEPT
# allow radvd dns from lan
/sbin/ip6tables -A INPUT -s IPV4NET -p udp -m multiport --dports 53,58 -j ACCEPT

/sbin/iptables-restore < /etc/iptables/rules
/usr/bin/supervisord -j /var/run/supervisord.pid -c /etc/supervisord.conf
